### ISSUE TITLE
InfiniR Alioth v2.93 flashed into POCO F3 but there is no kernelSU, this is a failure of the version

### ISSUE THREAD

**Issue by Kwisma** [raystef66/InfiniR_kernel_alioth#18]
InfiniR Alioth v2.93 flashed into POCO F3 without kernelSU, this version is a failure. InfiniR Alioth v2.92 has no problem and works normally.

**Comment by raystef66** [comment]
Am on 2.93 and kSU is present.
![Image8802394551575958408](https://github.com/user-attachments/assets/c43090df-6abb-459c-a157-3dbafa820611)
