### ISSUE TITLE
KernelSU - Unsupported on V1.01 ... working on V1.0.2 but can't install modules

### ISSUE THREAD

**Issue by zd3sf** [raystef66/InfiniR_kernel_alioth#19]
Poco F3
Crdroid 10.8 Sep142024 build
Kernel InfinR v2.96

Error: Unsupported - KSU only supports GKI kernels now

Updating KSU to V1.0.2 resolves the support issue but we are unable to install modules because KSU dropped support for non-GKI devices

**Comment by raystef66** [comment]
The only one working is 1.0.1 - stick on that one.
Also update to latest build of 10.9.

**Comment by zd3sf** [comment]
No worries. I rooted with Magisk. I cant update to 10.9 because CrDroid 10.9 breaks VoLTE (Error IMS registration is null) and its not your ROM. that is a problem... I tried 10.9 on Pixel 6Pro and Poco F3 on both T-mobile and ATT and both have VoLTE fail 2-3 days after working initially. I think theyre's an upstream change in Crdroid that breaks VoLTE and makes "phone services" crash
